"""A small zh-TW staff directory, and the lookup behind `search_contacts`.

500 rows in `directory.csv`, generated by `make_directory.py` from real zh-TW
surname frequencies -- 陳林黃張李王 are about a third of Taiwan, and that frequency
is what produces collisions and near-homophones naturally at scale. 10 names are
shared by 21 people. A handful are hand-placed fixtures the tests pin: 陳怡君 in
three departments, 林建宏 in two, and 張志強/張志祥 one easily-misheard syllable
apart. A directory where every name is unique would never exercise the
disambiguation turn, which is the part worth demonstrating.

Matching is phonetic as well as literal, because the query arrives from speech:
the model hears 「黃小華」 and may write 「王小華」 (huang/wang), or 「陳」 for 「程」.
Exact hits win; otherwise names are compared by pinyin with rapidfuzz, so a
one-syllable slip still finds the person.

Names here are invented for the demo. Extensions are 4-digit and internal.
"""

from __future__ import annotations

import csv
from dataclasses import asdict, dataclass
from pathlib import Path

from pypinyin import Style, lazy_pinyin
from rapidfuzz import fuzz

DEPARTMENTS = ("研發部", "行銷部", "業務部", "人資部", "財務部", "客服部", "設計部", "法務部")


@dataclass(frozen=True)
class Contact:
    name: str
    ext: str
    dept: str
    title: str = ""
    english: str = ""

    def as_dict(self) -> dict:
        return asdict(self)


DIRECTORY_CSV = Path(__file__).with_name("directory.csv")


def _load() -> list[Contact]:
    """Read the directory. Regenerate it with tools/make_directory.py."""
    with DIRECTORY_CSV.open(encoding="utf-8") as fh:
        return [Contact(r["name"], r["ext"], r["dept"], r["title"],
                        r.get("english", ""))
                for r in csv.DictReader(fh)]


CONTACTS: list[Contact] = _load()


def _pinyin(text: str) -> str:
    """Toneless pinyin, so a tone confusion (黃/王) still compares equal-ish."""
    return " ".join(lazy_pinyin(text, style=Style.NORMAL))


_PINYIN = {c.name: _pinyin(c.name) for c in CONTACTS}

# A floor alone cannot separate a mishearing from a different colleague once the
# directory is large: measured over 500 rows, the intended match scores 96-100
# while the best WRONG one reaches 87-96 (林健宏 hits 林建宏 at 100 and 林佳宏 at
# 96). So the floor only removes noise, and the decision is made by RANK: keep
# the best match and anything within a few points of it, which is the band a real
# homophone lives in.
PHONETIC_FLOOR = 85
TOP_MARGIN = 3


def search(query: str = "", department: str = "", title: str = "") -> list[dict]:
    """Contacts matching a name, English name, department and/or job title.

    Callers ask in all of these ways -- 「陳怡君」, 「Stella」, 「研發部的架構師」 --
    so `query` matches a Chinese OR English name while `department` and `title`
    filter. At least one of the three is required: an argument-less call must not
    return the whole directory.

    Returns every match. Deciding between them is the caller's job, and for the
    attendant that means asking the user rather than guessing.
    """
    q = (query or "").strip()
    dept = (department or "").strip()
    role = (title or "").strip()
    if not (q or dept or role):
        return []

    pool = [c for c in CONTACTS if not dept or dept in c.dept or c.dept in dept]
    if role:
        pool = [c for c in pool if role in c.title or c.title in role]
    if not q:
        # Filters only: 「研發部的架構師是誰」. Still every match, so a broad filter
        # comes back broad and the model has to narrow it with the user.
        return [c.as_dict() for c in pool]

    # English names are how many colleagues are actually known; match them
    # case-insensitively before falling through to the Chinese paths.
    ql = q.casefold()
    english = [c for c in pool if c.english and c.english.casefold() == ql]
    if english:
        return [c.as_dict() for c in english]

    exact = [c for c in pool if c.name == q]
    if exact:
        return [c.as_dict() for c in exact]

    # Substring, for a partial name or a given name on its own.
    partial = [c for c in pool if q in c.name]
    if partial:
        return [c.as_dict() for c in partial]

    # Phonetic: the query came from speech, so a wrong character is expected.
    qp = _pinyin(q)
    scored = [(fuzz.ratio(qp, _PINYIN[c.name]), c) for c in pool]
    ranked = sorted((sc for sc in scored if sc[0] >= PHONETIC_FLOOR), key=lambda sc: -sc[0])
    if ranked:
        cutoff = max(PHONETIC_FLOOR, ranked[0][0] - TOP_MARGIN)
        return [c.as_dict() for score, c in ranked if score >= cutoff]

    # The name matched nothing, but the filters did. That combination happens when
    # a misheard word lands in `query`: asked for 「研發部的資深工程師分機」 the model
    # searched name=分基地 title=資深工程師 and got nothing, when the title alone
    # answers the question. Falling back to the filters beats saying 查無此人.
    if dept or role:
        return [c.as_dict() for c in pool]
    return []


def departments_of(matches: list[dict]) -> list[str]:
    """The distinct departments among matches -- the choices to offer the user."""
    seen: list[str] = []
    for m in matches:
        if m["dept"] not in seen:
            seen.append(m["dept"])
    return seen
