"""The call -> observe -> answer loop, talking to the model server directly.

This replaces qwen-agent's Assistant. That framework was doing very little for us:
with use_raw_api its Qwen-specific dialect (NousFnCallPrompt) was instantiated and
never used, because tool calls are generated by the server under the model's own
chat template. What it did contribute was a cumulative snapshot protocol -- each
iteration yielding the whole message list again -- which the streaming code had to
diff to recover deltas, plus a bug where tool results were labelled `id` instead of
`tool_call_id` and were rejected by strict providers.

Driving /v1/chat/completions ourselves is both smaller and more direct: deltas
arrive as deltas, tool_call_id is emitted correctly by construction, the step count
is bounded here rather than through an environment variable read at import time,
and validation and sanitisation happen at the one place tool results enter the
prompt.

Event contract (unchanged, so the UI and ling_streaming keep working):

    llm_reasoning {text}            deliberation, never spoken
    llm_delta     {text}            incremental answer text
    llm_delta     {text:"", reset}  discard what was buffered: it was not the answer
    tool_call / tool_result         emitted by the tools themselves

Returns the final answer text.
"""

from __future__ import annotations

import base64
import io
import json
import os
import wave

import httpx
from loguru import logger

from agent._shared import emit as _emit
from agent.tool_guard import ToolArgumentError, sanitize_tool_output, validate_args

# A turn is one question. Three steps is enough for tool -> observe -> answer, and
# bounding it here rather than in an env var read at import time is the point: the
# old ceiling was 20, which is how an 8-call loop once happened.
MAX_STEPS = int(os.getenv("LLM_AGENT_MAX_STEPS", "3"))

# Longest pre-tool utterance that is spoken rather than discarded. An
# acknowledgement is a clause; deliberation is a paragraph. 0 restores the old
# behaviour of dropping everything before a tool call.
PREAMBLE_MAX_CHARS = int(os.getenv("LLM_TOOL_PREAMBLE_MAX", "40"))
HTTP_TIMEOUT = float(os.getenv("LLM_REQUEST_TIMEOUT", "45"))


def _tool_schemas(tools: dict) -> list[dict]:
    return [{"type": "function",
             "function": {"name": t.name, "description": t.description,
                          "parameters": t.parameters}}
            for t in tools.values()]


def _run_tool(tool, raw_args: str) -> str:
    """Validate, execute, and return output that is safe to put in the prompt."""
    try:
        args = validate_args(raw_args, tool.parameters, tool.name)
    except ToolArgumentError as e:
        logger.warning("rejected tool arguments: {}", e)
        return sanitize_tool_output(f"tool argument error: {e}")
    try:
        out = tool.call(args)
    except Exception as e:                      # a tool must not kill the turn
        logger.exception("tool {} failed: {}", tool.name, e)
        return sanitize_tool_output(f"tool error: {type(e).__name__}")
    # The tools already sanitise their own return value; this is idempotent and
    # covers a tool that forgets to.
    text = out if isinstance(out, str) else json.dumps(out, ensure_ascii=False)
    return text if text.startswith("<tool_output>") else sanitize_tool_output(text)


def audio_content(pcm16: bytes, sample_rate: int = 16000) -> dict:
    """One OpenAI `input_audio` part from raw PCM16, for a spoken prompt.

    Wrapped as a WAV because that is the container llama.cpp's multimodal path
    accepts; `audio_url` is refused, and raw PCM has no sample-rate header to read.
    """
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(sample_rate)
        w.writeframes(pcm16)
    return {"type": "input_audio",
            "input_audio": {"data": base64.b64encode(buf.getvalue()).decode(), "format": "wav"}}


def run_turn(messages: list[dict], tools: dict, *, api_base: str, model: str,
             api_key: str = "none", generate_cfg: dict | None = None) -> str:
    """One agent turn. Emits events as it goes; returns the final answer text.

    A message's content may be a list of parts, so a spoken turn is just
    ``[audio_content(pcm)]`` in place of text -- the tool schemas, the loop and the
    sanitising are identical. Measured on Gemma 4 E4B, a tool routes from speech
    alone in 0.2-0.6 s, so audio input does not cost the tools.
    """
    cfg = dict(generate_cfg or {})
    schemas = _tool_schemas(tools)
    convo = list(messages)
    spoke_preamble = False   # at most one spoken acknowledgement per turn
    answer = ""

    for _step in range(MAX_STEPS):
        body = {"model": model, "messages": convo, "stream": True, **cfg}
        if schemas:
            body["tools"] = schemas
        content, reasoning, calls = "", "", {}
        streamed = 0

        with httpx.Client(timeout=HTTP_TIMEOUT) as client:
            with client.stream("POST", f"{api_base.rstrip('/')}/chat/completions",
                               json=body,
                               headers={"Authorization": f"Bearer {api_key}"}) as r:
                r.raise_for_status()
                for line in r.iter_lines():
                    if not line or not line.startswith("data:"):
                        continue
                    payload = line[5:].strip()
                    if payload == "[DONE]":
                        break
                    try:
                        chunk = json.loads(payload)
                    except json.JSONDecodeError:
                        continue
                    delta = ((chunk.get("choices") or [{}])[0]).get("delta") or {}
                    rc = delta.get("reasoning_content")
                    if rc:
                        reasoning += rc
                        _emit({"type": "llm_reasoning", "text": rc})
                    piece = delta.get("content")
                    if piece:
                        content += piece
                        # Stream the answer as it is produced, so TTS can start
                        # before the turn finishes.
                        _emit({"type": "llm_delta", "text": piece})
                        streamed += len(piece)
                    for tc in delta.get("tool_calls") or []:
                        # Streamed tool calls arrive in fragments keyed by index.
                        slot = calls.setdefault(tc.get("index", 0),
                                                {"id": "", "name": "", "args": ""})
                        if tc.get("id"):
                            slot["id"] = tc["id"]
                        fn = tc.get("function") or {}
                        if fn.get("name"):
                            slot["name"] = fn["name"]
                        if fn.get("arguments"):
                            slot["args"] += fn["arguments"]

        if not calls:
            answer = content
            break

        # The model wants tools, so whatever it streamed this step was preamble,
        # not the answer. Two kinds turn up there and they need opposite handling.
        #
        # A short acknowledgement -- 「好的，我查一下台北的天氣」 -- is worth speaking:
        # a tool turn is several seconds of silence otherwise, and saying something
        # immediately is the difference between "thinking" and "broken". The model
        # is asked for one in the system message.
        #
        # Anything longer is the failure 829baf1 fixed: reasoning or scaffolding
        # leaking into content and being read out as if it were the answer. The
        # bound is on LENGTH, not on wording -- there is no phrase list here, and a
        # model that starts deliberating simply exceeds it and is dropped.
        if streamed:
            ack = content.strip()
            # Only the first tool step may speak. A turn that calls two tools
            # otherwise says it twice -- an exported session shows
            # 「好的，我查一下。好的，我查一下。」 before a single answer.
            if (PREAMBLE_MAX_CHARS and not spoke_preamble
                    and 0 < len(ack) <= PREAMBLE_MAX_CHARS):
                spoke_preamble = True
                logger.debug("keeping tool preamble: %r", ack)
            else:
                _emit({"type": "llm_delta", "text": "", "reset": True})

        assistant_msg: dict = {"role": "assistant", "content": content or ""}
        assistant_msg["tool_calls"] = [
            {"id": c["id"] or f"call_{i}", "type": "function",
             "function": {"name": c["name"], "arguments": c["args"] or "{}"}}
            for i, c in sorted(calls.items())
        ]
        convo.append(assistant_msg)

        for i, c in sorted(calls.items()):
            tool = tools.get(c["name"])
            if tool is None:
                logger.warning("model called an unknown tool: {!r}", c["name"])
                result = sanitize_tool_output(f"no such tool: {c['name']}")
            else:
                result = _run_tool(tool, c["args"])
            convo.append({"role": "tool",
                          # tool_call_id, not id: the OpenAI schema requires it and
                          # strict servers reject the message without it.
                          "tool_call_id": c["id"] or f"call_{i}",
                          "name": c["name"], "content": result})
    else:
        logger.warning("tool loop hit its %d-step ceiling; answering with what we have", MAX_STEPS)
        answer = content

    return answer
